/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.finance.swing;

import org.finance.controller.UsuarioController;
import org.finance.model.entities.EnderecoEntity;
import org.finance.model.entities.UsuarioEntity;

import javax.swing.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Date;

import static org.finance.swing.Login.userSystem;

/**
 *
 * @author Victor
 */
public class DadosView extends javax.swing.JFrame {

    private UsuarioController usuarioController;
    /**
     * Creates new form CadastrarView
     */
    public DadosView() {
        initComponents();
        mostrarDados();
        usuarioController = new UsuarioController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeDeUsuario = new javax.swing.JTextField();
        dataDeNascimento = new javax.swing.JFormattedTextField();
        cpf = new javax.swing.JFormattedTextField();
        nome = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        complemento = new javax.swing.JTextField();
        nomeDaRua = new javax.swing.JTextField();
        bairro = new javax.swing.JTextField();
        cep = new javax.swing.JTextField();
        estado = new javax.swing.JTextField();
        pais = new javax.swing.JTextField();
        numeroDaCasa = new javax.swing.JTextField();
        cidade = new javax.swing.JTextField();
        cadastrar = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeDeUsuario.setEditable(false);
        nomeDeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDeUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(nomeDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 270, 30));

        dataDeNascimento.setEditable(false);
        try {
            dataDeNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataDeNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDeNascimentoActionPerformed(evt);
            }
        });
        getContentPane().add(dataDeNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 270, 30));

        cpf.setEditable(false);
        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpf.setText("123.465.864-25");
        getContentPane().add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 270, 30));

        nome.setEditable(false);
        nome.setToolTipText("");
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 270, 30));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 270, 30));
        getContentPane().add(complemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 280, 30));
        getContentPane().add(nomeDaRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 280, 30));
        getContentPane().add(bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 280, 30));
        getContentPane().add(cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 280, 30));
        getContentPane().add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 280, 30));
        getContentPane().add(pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 280, 30));
        getContentPane().add(numeroDaCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 280, 30));
        getContentPane().add(cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 280, 30));

        cadastrar.setContentAreaFilled(false);
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 543, 180, 30));

        backButton.setAutoscrolls(true);
        backButton.setContentAreaFilled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dadosUsuario.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeDeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDeUsuarioActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void mostrarDados() {
        // mostrar endereco
        nomeDaRua.setText(userSystem.getEndereco().getRua());
        cep.setText(userSystem.getEndereco().getCep());
        cidade.setText(userSystem.getEndereco().getCidade());
        estado.setText(userSystem.getEndereco().getEstado());
        pais.setText(userSystem.getEndereco().getPais());
        complemento.setText(userSystem.getEndereco().getComplemento());
        numeroDaCasa.setText(userSystem.getEndereco().getNumero());

        //mostrar dados usuario;
        nome.setText(userSystem.getNome());
        cpf.setText(userSystem.getCpf());
        LocalDate localDate = userSystem.getDataNascimento();
        Date date = Date.from(localDate.atStartOfDay(ZoneId.systemDefault()).toInstant());
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        dataDeNascimento.setText(dateFormat.format(date));
        email.setText(userSystem.getEmail());
        nomeDeUsuario.setText(userSystem.getNomeUsuario());

    }

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        UsuarioEntity usuario = userSystem; // Obtém o usuário atual

        // Verifica e atualiza os campos de endereço se não forem nulos
        if (!nomeDaRua.getText().isEmpty()) {
            usuario.getEndereco().setRua(nomeDaRua.getText());
        }
        if (!cep.getText().isEmpty()) {
            usuario.getEndereco().setCep(cep.getText());
        }
        if (!cidade.getText().isEmpty()) {
            usuario.getEndereco().setCidade(cidade.getText());
        }
        if (!estado.getText().isEmpty()) {
            usuario.getEndereco().setEstado(estado.getText());
        }
        if (!pais.getText().isEmpty()) {
            usuario.getEndereco().setPais(pais.getText());
        }
        if (!complemento.getText().isEmpty()) {
            usuario.getEndereco().setComplemento(complemento.getText());
        }
        if (!numeroDaCasa.getText().isEmpty()) {
            usuario.getEndereco().setNumero(numeroDaCasa.getText());
        }

        // Verifica e atualiza o email se não for nulo
        if (!email.getText().isEmpty()) {
            usuario.setEmail(email.getText());
        }

        // Persiste as alterações no banco de dados
        try {
            usuarioController.updateUser(usuario);
            JOptionPane.showMessageDialog(this, "Dados atualizados com sucesso!");
            this.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar os dados: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

        this.setVisible(false);
    }//GEN-LAST:event_cadastrarActionPerformed

    private void dataDeNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDeNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataDeNascimentoActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DadosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DadosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DadosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DadosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DadosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField bairro;
    private javax.swing.JButton cadastrar;
    private javax.swing.JTextField cep;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField complemento;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JFormattedTextField dataDeNascimento;
    private javax.swing.JTextField email;
    private javax.swing.JTextField estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField nomeDaRua;
    private javax.swing.JTextField nomeDeUsuario;
    private javax.swing.JTextField numeroDaCasa;
    private javax.swing.JTextField pais;
    // End of variables declaration//GEN-END:variables
}
