/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.finance.swing;

import org.finance.controller.TiposDeDespesaController;
import org.finance.model.entities.TiposDeDespesaEntity;

import javax.swing.*;

import java.util.List;

import static org.finance.swing.Login.userSystem;

/**
 *
 * @author Victor
 */
public class DespesaView extends javax.swing.JFrame {

    private TiposDeDespesaController tiposDeDespesaController;
    /**
     * Creates new form DespesaView
     */
    public DespesaView() {
        tiposDeDespesaController = new TiposDeDespesaController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        visualizaButton = new javax.swing.JButton();
        cadastrarButton = new javax.swing.JButton();
        excluirButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        visualizaButton.setContentAreaFilled(false);
        visualizaButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                visualizaButtonComponentShown(evt);
            }
        });
        visualizaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(visualizaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 240, 50));

        cadastrarButton.setContentAreaFilled(false);
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 263, 240, 60));

        excluirButton.setContentAreaFilled(false);
        excluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirButtonActionPerformed(evt);
            }
        });
        getContentPane().add(excluirButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 240, 60));

        voltarButton.setContentAreaFilled(false);
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/despesas.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void visualizaButtonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_visualizaButtonComponentShown
        
    }//GEN-LAST:event_visualizaButtonComponentShown

    private void visualizaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizaButtonActionPerformed
        if (userSystem.getTiposDeDespesaEntities() != null) {
            StringBuilder mensagem = new StringBuilder("Tipos de despesa:\n");
            for (TiposDeDespesaEntity tipoDeDespesa : userSystem.getTiposDeDespesaEntities()) {
                mensagem.append("- ").append(tipoDeDespesa.getNomeDaDespesa()).append("\n");
            }
            JOptionPane.showMessageDialog(this, mensagem.toString(), "Tipos de Despesa", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "A lista de tipos de despesa está vazia.", "Lista Vazia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_visualizaButtonActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        String nomeCategoria = JOptionPane.showInputDialog(this, "Digite o nome da nova categoria de despesa:");

        if (nomeCategoria != null && !nomeCategoria.isEmpty()) {
            TiposDeDespesaEntity novaCategoria = new TiposDeDespesaEntity(nomeCategoria, userSystem);


            try {
                tiposDeDespesaController.creatTipo(novaCategoria);
                JOptionPane.showMessageDialog(this, "Categoria de despesa cadastrada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                userSystem.setTiposDeDespesaEntities(tiposDeDespesaController.findAll());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar categoria de despesa: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nome da categoria de despesa inválido.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void excluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirButtonActionPerformed
        List<TiposDeDespesaEntity> categorias = tiposDeDespesaController.findAll();

        if (categorias.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Não há categorias de despesa para excluir.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        StringBuilder mensagem = new StringBuilder("IDs das categorias de despesa:\n");
        for (TiposDeDespesaEntity categoria : categorias) {
            mensagem.append("- ID: ").append(categoria.getId()).append(", Nome: ").append(categoria.getNomeDaDespesa()).append("\n");
        }

        String idCategoria = JOptionPane.showInputDialog(this, mensagem.toString(), "Digite o ID da categoria a ser excluída:");

        if (idCategoria != null && !idCategoria.isEmpty()) {
            try {
                Long id = Long.parseLong(idCategoria);
                boolean categoriaEncontrada = false;

                for (TiposDeDespesaEntity categoria : categorias) {
                    if (categoria.getId().equals(id)) {
                        tiposDeDespesaController.delete(categoria);
                        categoriaEncontrada = true;
                        break;
                    }
                }

                if (categoriaEncontrada) {
                    JOptionPane.showMessageDialog(this, "Categoria de despesa excluída com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    userSystem.setTiposDeDespesaEntities(tiposDeDespesaController.findAll());
                } else {
                    JOptionPane.showMessageDialog(this, "ID da categoria de despesa não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Por favor, insira um ID válido.", "Erro", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir categoria de despesa: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_excluirButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_voltarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DespesaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DespesaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DespesaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DespesaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DespesaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JButton excluirButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton visualizaButton;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
