/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.finance.swing;

import org.finance.controller.UsuarioController;
import org.finance.model.entities.UsuarioEntity;

import javax.swing.*;

/**
 *
 * @author Victor
 */
public class Login extends javax.swing.JFrame {

    private UsuarioController usuarioController;
    public static UsuarioEntity userSystem = null;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        usuarioController = new UsuarioController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        logarConta = new javax.swing.JButton();
        realizarCadastro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 360, 40));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 360, 40));

        logarConta.setContentAreaFilled(false);
        logarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logarContaActionPerformed(evt);
            }
        });
        getContentPane().add(logarConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 180, 40));

        realizarCadastro.setContentAreaFilled(false);
        realizarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(realizarCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 150, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 804, 602));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void logarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logarContaActionPerformed

        String email = jTextField1.getText();
        String senha = new String(jPasswordField1.getPassword());

        UsuarioEntity usuario = usuarioController.login(email, senha);

        if(usuario != null) {
            userSystem = usuario;
            DashboardView dashboardView = new DashboardView();
            dashboardView.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Email ou senha incorretos! ");
        }

    }//GEN-LAST:event_logarContaActionPerformed

    private void realizarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarCadastroActionPerformed
        CadastrarView telaDeCadastro = new CadastrarView();
        telaDeCadastro.setVisible(true);
    }//GEN-LAST:event_realizarCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton logarConta;
    private javax.swing.JButton realizarCadastro;
    // End of variables declaration//GEN-END:variables
}
